# Generated by Django 4.1.5 on 2023-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('susep', models.CharField(max_length=20)),
                ('expiracaoDeVenda', models.DateTimeField()),
                ('valorMinimoAporteInicial', models.IntegerField()),
                ('valorMinimoAporteExtra', models.IntegerField()),
                ('idadeDeEntrada', models.IntegerField()),
                ('idadeDeSaida', models.IntegerField()),
                ('carenciaInicialDeResgate', models.IntegerField()),
                ('carenciaEntreResgates', models.IntegerField()),
            ],
        ),
    ]
