# Generated by Django 4.1.5 on 2023-01-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorResgate', models.IntegerField()),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.contratacaoplano')),
            ],
        ),
        migrations.CreateModel(
            name='AporteExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorAporte', models.IntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.cliente')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.contratacaoplano')),
            ],
        ),
    ]
